sudo: required
language: scala

scala:
  - 2.12.4

before_cache:
  - rm -fr $HOME/.gradle/caches/

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

script:
  - "./gradlew build"

